### ISSUE TITLE
tutorial-dnn-object-detection-live issue when running it on SSD-Mobilenet.onnx

### ISSUE THREAD

**Issue by jnader** [lagadic/visp#1023]
There's an issue when trying to run `tutorial-dnn-object-detection-live` with `ssd-mobilenet.onnx` available in [visp-images](https://github.com/lagadic/visp-images).

The following is a description of the issue:

- On `OpenCV 4.2.0` we face a model import error as shown below:
```
  what(): OpenCV(4.2.0) ../modules/dnn/src/onnx/onnx_importer.cpp:101: error: (-211:One of the arguments' values is out of range) Input is out of OpenCV 32S range in function 'convertInt64ToInt32'
```
Apparently, in this version of OpenCV, the model cannot be loaded and the issue arises.

- On `OpenCV 4.5.2`, when building OpenCV from source, we face another type of error. This time, the model is imported correctly, but the output layer is not taken in consideration in `vpDetectorDNN.cpp`, specifically in `vpDetectorDNN::postProcess()` function. The error is as follows:
```
  what(): OpenCV(4.5.2) ../modules/detection/src/dnn/vpDetectorDNN.cpp:272: error: (-213:The function/feature is not implemented) Unknown output layer type: Softmax in function `postProcess'
```

- On `OpenCV 4.5.5`, when building OpenCV from source again, this time the latest version, the error is again about unknown output layer type, but it changed for the same model:
```
  what(): OpenCV(4.5.5) ../modules/detection/src/dnn/vpDetectorDNN.cpp:272: error: (-213:The function/feature is not implemented) Unknown output layer type: Identity in function `postProcess'
```
Apparently, there were some changes concerning the way a `.onnx` model is parsed in opencv and it influences the type of the layer as seen by opencv (for the same model).

I am currently working on adding a section in `postProcess()` that should be working with `4.5.2` and `4.5.5` versions of OpenCV with output layer types `Softmax` and `Identity`.

**Comment by fspindle** [comment]
Fixed in #1024
