### ISSUE TITLE
Build error with libboost_thread-mt.a

### ISSUE THREAD

**Issue by fspindle** [lagadic/visp#466]
This error occurs with an up to date Ubuntu 16.04 LTS.

It occurs when cxx11 and Ogre3D 3rd-party are enabled:

```Linking CXX shared library ../../lib/libvisp_ar.so
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libboost_thread-mt.a(thread.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libboost_thread-mt.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
modules/ar/CMakeFiles/visp_ar.dir/build.make:280: recipe for target 'lib/libvisp_ar.so.3.2.0' failed
make[3]: *** [lib/libvisp_ar.so.3.2.0] Error 1
```
I sounds that `libboost_thread-mt.a` is not compatible with cxx11 enabled.

**Comment by fspindle** [comment]
Changes introduced in d19d94c lead to new build errors

```
In file included from visp/modules/sensor/src/rgb-depth/realsense/vpRealSense.cpp:43:
visp/modules/sensor/include/visp3/sensor/vpRealSense.h:57:10: fatal error: 'pcl/common/projection_matrix.h' file not found
#include <pcl/common/projection_matrix.h>
```

The solution that seems working is to turn `Boost_USE_MULTITHREADED` to `ON` after Ogre3D detection
