### ISSUE TITLE
Unable to build with PCL 1.15 and cxx14 standard

### ISSUE THREAD

**Issue by fspindle** [lagadic/visp#1819]
This issue can be reproduced on macOS Sequoia 15.7.1 after updating the brew packages.
```
% brew info pcl
==> pcl: stable 1.15.1 (bottled), HEAD
```

When trying to build ViSP enabling cxx14 we got the following build issues:
```
% cmake ../visp -DUSE_CXX_STANDARD=14
...
In file included from /Users/visp_ws/visp/modules/core/src/display/vpDisplay.cpp:41:
In file included from /Users/visp_ws/visp/modules/core/include/visp3/core/vpImageConvert.h:95:
/opt/homebrew/include/pcl-1.15/pcl/pcl_config.h:7:4: error: C++ standard too low (PCL requires 201703L or above)
    7 |   #error C++ standard too low (PCL requires 201703L or above)
      |    ^
```
