### ISSUE TITLE
Android Build Error with ViSP 3.6.x

### ISSUE THREAD

**Issue by Som5ra** [lagadic/visp#1460]
when python3 build_sdk.py --config ndk-23.config.py...
```
In file included from /visp_ws/visp-android/visp-3.6.0/modules/core/src/tools/file/vpIoTools.cpp:58:
/Unity/Hub/Editor/2022.3.20f1/Editor/Data/PlaybackEngines/AndroidPlayer/NDK/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/fstream:952:20: error: use of undeclared identifier 'ftello'; did you mean 'ftell'?
    pos_type __r = ftello(__file_);
```

but the android building works well with 3.5.0. Is this a unsolved issue with 3.6.x? Thanks

**Comment by Som5ra** [comment]
Solved by specify: ANDROID_PLATFORM=24 when building
