### ISSUE TITLE
Unable to build with Eigen3 5.0.0 release

### ISSUE THREAD

**Issue by fspindle** [lagadic/visp#1818]
This issue can be reproduced on macOS Sequoia 15.7.1 after updating the brew packages.
```
% brew info eigen
==> eigen: stable 5.0.0 (bottled), HEAD
```

Before the brew upgrade, Eigen3 3.4.0 version was used.

Checking `ViSP-3rd-party.txt` file we can see that Eigen is detected, but that ViSP is unable to detect its version.

```
% cat ViSP-third-party.txt
  Mathematics:
    Blas/Lapack:                 yes
    \- Use MKL:                  no
    \- Use OpenBLAS:             no
    \- Use Atlas:                no
    \- Use Netlib:               no
    \- Use GSL:                  yes (ver 2.8)
    \- Use Lapack (built-in):    no
    Use Eigen3:                  yes (ver ..)
    Use OpenCV:                  yes (ver 4.12.0)
 
  Library dirs:
    Eigen3 dir:                  /opt/homebrew/share/eigen3/cmake
```

More over when build `visp_core` module we got build issues:

```
% make visp_core
In file included from /Users/visp_ws/visp/modules/core/src/display/vpDisplay.cpp:41:
In file included from /Users/visp_ws/visp/modules/core/include/visp3/core/vpImageConvert.h:96:
In file included from /opt/homebrew/include/pcl-1.15/pcl/point_types.h:354:
In file included from /opt/homebrew/include/pcl-1.15/pcl/impl/point_types.hpp:41:
/opt/homebrew/include/pcl-1.15/pcl/memory.h:49:10: fatal error: 'Eigen/Core' file not found
   49 | #include <Eigen/Core>  // for EIGEN_MAKE_ALIGNED_OPERATOR_NEW
      |          ^~~~~~~~~~~~
```
