### ISSUE TITLE
Unable to build with pcl 1.12.1 on macOS

### ISSUE THREAD

**Issue by fspindle** [lagadic/visp#977]
CMake configuration shows that `pcl 1.12.1` is detected
```
$ grep PCL ViSP-third-party.txt 
    Use PCL:                     yes (ver 1.12.1)
```
but build fails:
```
In file included from /Users/visp_ws/visp/modules/sensor/src/rgb-depth/realsense/vpRealSense2.cpp:44:
/Users/visp_ws/visp/modules/sensor/include/visp3/sensor/vpRealSense2.h:47:10: fatal error: 'pcl/common/common_headers.h' file not found
#include <pcl/common/common_headers.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

See issue reported to pcl developers: https://github.com/PointCloudLibrary/pcl/issues/5129

`pcl 1.12.1` has a dependency to `qt5` that is keg-only, which means it was not symlinked into `/usr/local`. As a consequence, ViSP will be not able to detect `pcl` headers location leading to this build issue. The solution to complete `pcl 1.12.1` installation is here to run the additional commands:
```
$ brew link --force qt5
$ sudo ln -s $(brew --prefix qt5)/mkspecs /usr/local/mkspecs
$ sudo ln -s $(brew --prefix qt5)/plugins /usr/local/plugins
```
But this is not enough. Once PCL is detected, there is a problem with `vtk 9.1.0`:
- headers are not found
  ```
  In file included from /Users/visp_ws/visp/modules/sensor/test/rgb-depth/testOccipitalStructure_Core_pcl.cpp:50:
  In file included from /usr/local/include/pcl-1.12/pcl/visualization/cloud_viewer.h:39:
  In file included from /usr/local/include/pcl-1.12/pcl/visualization/pcl_visualizer.h:48:
  In file included from /usr/local/include/pcl-1.12/pcl/visualization/common/actor_map.h:40:
    /usr/local/include/pcl-1.12/pcl/visualization/point_cloud_geometry_handlers.h:49:10: fatal error: 'vtkSmartPointer.h' file not found
    #include <vtkSmartPointer.h>
  ```
- build fails due to `vtkDataArray` that uses the same macro (`AllValues`) as X. The solution is to include X headers after `vtkDataArray`. 
  ```
  In file included from /Users/fspindle/soft/visp/visp_ws/test-pr/visp-fspindle/modules/sensor/test/rgb-depth/testRealSense2_SR300.cpp:55:
  In file included from /usr/local/include/pcl-1.12/pcl/visualization/cloud_viewer.h:39:
  In file included from /usr/local/include/pcl-1.12/pcl/visualization/pcl_visualizer.h:48:
  In file included from /usr/local/include/pcl-1.12/pcl/visualization/common/actor_map.h:40:
  In file included from /usr/local/include/pcl-1.12/pcl/visualization/point_cloud_geometry_handlers.h:50:
  In file included from /usr/local/include/vtk-9.1/vtkPoints.h:29:
    /usr/local/include/vtk-9.1/vtkDataArray.h:602:1: error: declaration of anonymous struct must be a definition struct AllValues
  ```

**Comment by fspindle** [comment]
Fixed with PR #975
