### ISSUE TITLE
visp failing to build on opencv 4.9.0

### ISSUE THREAD

**Issue by timsutton** [lagadic/visp#1309]
👋 Hello, I have been working to update Homebrew's build of OpenCV to 4.9.0, and VISP 3.6.0 seems to be hitting compilation errors on Apple Silicon (arm64) due to some changes between 4.8.1 and 4.9.0. Would you have any suggestions to help resolve it?

The errors look like perhaps due to changes in types:

```
[ 93%] Building CXX object modules/tt/CMakeFiles/visp_tt.dir/src/tools/vpTemplateTrackerBSpline.cpp.o
cd /tmp/visp-20240109-4377-n8b39c/visp-3.6.0/modules/tt && /opt/homebrew/Library/Homebrew/shims/mac/super/clang++ -Dvisp_EXPORTS -I/tmp/visp-20240109-4377-n8b39c/visp-3.6.0/include -I/opt/homebrew/opt/eigen/include/eigen3 -I/tmp/visp-20240109-4377-n8b39c/visp-3.6.0/modules/tracker/tt/include -I/tmp/visp-20240109-4377-n8b39c/visp-3.6.0/modules/tracker/tt/src -I/tmp/visp-20240109-4377-n8b39c/visp-3.6.0/modules/tt -I/tmp/visp-20240109-4377-n8b39c/visp-3.6.0/modules/core/include -I/tmp/visp-20240109-4377-n8b39c/visp-3.6.0/modules/io/include -I/tmp/visp-20240109-4377-n8b39c/visp-3.6.0/modules/tracker/me/include -I/tmp/visp-20240109-4377-n8b39c/visp-3.6.0/modules/tracker/blob/include -I/tmp/visp-20240109-4377-n8b39c/visp-3.6.0/modules/visual_features/include -I/tmp/visp-20240109-4377-n8b39c/visp-3.6.0/modules/vision/include -I/opt/homebrew/Cellar/opencv/4.9.0/include/opencv4 -I/opt/homebrew/opt/jpeg-turbo/include -I/opt/homebrew/opt/libpng/include -Wall -Wextra -Xclang -fopenmp -std=c++17 -fvisibility=hidden -fPIC -O3 -DNDEBUG -std=c++17 -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk -fPIC -MD -MT modules/tt/CMakeFiles/visp_tt.dir/src/tools/vpTemplateTrackerBSpline.cpp.o -MF CMakeFiles/visp_tt.dir/src/tools/vpTemplateTrackerBSpline.cpp.o.d -o CMakeFiles/visp_tt.dir/src/tools/vpTemplateTrackerBSpline.cpp.o -c /tmp/visp-20240109-4377-n8b39c/visp-3.6.0/modules/tracker/tt/src/tools/vpTemplateTrackerBSpline.cpp
/tmp/visp-20240109-4377-n8b39c/visp-3.6.0/modules/tracker/mbt/src/depth/vpMbtFaceDepthDense.cpp:521:34: error: invalid operands to binary expression ('const cv::v_float64x2' and 'cv::v_float64x2')
        cv::v_float64x2 va1 = vnz*vy - vny*vz;
                              ~~~^~~
/tmp/visp-20240109-4377-n8b39c/visp-3.6.0/modules/core/include/visp3/core/vpRotationVector.h:162:13: note: candidate function not viable: no known conversion from 'const cv::v_float64x2' to 'const double' for 1st argument
vpColVector operator*(const double &x, const vpRotationVector &v);
            ^
/tmp/visp-20240109-4377-n8b39c/visp-3.6.0/modules/core/include/visp3/core/vpMatrix.h:1205:10: note: candidate function not viable: no known conversion from 'const cv::v_float64x2' to 'const double' for 1st argument
vpMatrix operator*(const double &x, const vpMatrix &A);
         ^
/tmp/visp-20240109-4377-n8b39c/visp-3.6.0/modules/core/include/visp3/core/vpRotationMatrix.h:229:18: note: candidate function not viable: no known conversion from 'const cv::v_float64x2' to 'const double' for 1st argument
vpRotationMatrix operator*(const double &x, const vpRotationMatrix &R);
                 ^
/tmp/visp-20240109-4377-n8b39c/visp-3.6.0/modules/core/include/visp3/core/vpRowVector.h:341:25: note: candidate function not viable: no known conversion from 'const cv::v_float64x2' to 'const double' for 1st argument
VISP_EXPORT vpRowVector operator*(const double &x, const vpRowVector &v);
                        ^
/tmp/visp-20240109-4377-n8b39c/visp-3.6.0/modules/core/include/visp3/core/vpColVector.h:461:13: note: candidate function not viable: no known conversion from 'const cv::v_float64x2' to 'const double' for 1st argument
vpColVector operator*(const double &x, const vpColVector &v);
            ^
/tmp/visp-20240109-4377-n8b39c/visp-3.6.0/modules/tracker/mbt/src/depth/vpMbtFaceDepthDense.cpp:521:43: error: invalid operands to binary expression ('const cv::v_float64x2' and 'cv::v_float64x2')
        cv::v_float64x2 va1 = vnz*vy - vny*vz;
```

You can see the full output from the [build logs here](https://github.com/Homebrew/homebrew-core/actions/runs/7465501049/job/20314938741?pr=158712) and disclosing the `Full install --build-bottle visp output` section. Or [raw logs here](https://pipelinesghubeus21.actions.githubusercontent.com/revSbsLpzrFApLL6BmCvScWt72tRe3wYUv7fCdCtThtI5bydk7/_apis/pipelines/1/runs/1385257/signedlogcontent/54?urlExpires=2024-01-16T12%3A56%3A06.3673195Z&urlSigningMethod=HMACV1&urlSignature=l9CdRw9%2F4YYkLBN4FkCeYsyvpnEtZUrtE%2B8sXIrUM5k%3D).

(Full compare of OpenCV's changes is [here](https://github.com/opencv/opencv/compare/4.8.1..4.9.0) but it's big)

**Comment by s-trinh** [comment]
Does these changes https://github.com/lagadic/visp/pull/1310 solve this issue?

---

Related:
- https://github.com/opencv/opencv/pull/23310
- https://github.com/opencv/opencv/pull/23885
- https://github.com/opencv/opencv/pull/24371
